### ISSUE TITLE
Add link to network and build systems to the list

### ISSUE THREAD

**Issue by wjam** [jameslk/awesome-falsehoods#1]
These two blog posts could be added to the list, although they don't explain while the falsehoods are false.

[Falsehoods programmers believe about networks](http://blog.erratasec.com/2012/06/falsehoods-programmers-believe-about.html)
[Falsehoods programmers believe about build systems](http://pozorvlak.livejournal.com/174763.html)

**Comment by jameslk** [comment]
Added, thanks! :)

**Comment by jameslk** [comment]
Oh and regarding your point about explanations--that would be ideal for future articles. I think I would swap replacements in that go into more depth. Since there's not a lot of these type of articles yet, something is better than nothing. I'll add a note to the contributions section.
